### ISSUE TITLE
Support for existing SyncThing instance

### ISSUE THREAD

**Issue by QuentinWidlocher** [theCapypara/steamdeck-decky-syncthing#1]
Hi, I have a running SyncThing instance on my deck and this plugin tells me that SyncThing is not running.

I figured it may have something to do with conflicting instances of ST ? Do I have to stop mine and only use the plugins ?

**Comment by theCapypara** [comment]
Hi! Yes, you stop the one already running.

I designed it so that it works best with the Syncthing GTK Flatpak. You can use that one in Desktop mode, but it should stop automatically when switching to Gamescope.

If you set something else up to have it running in Gamescope, you'd need to disable that. Note that this plugin only works with the Flatpak version, so if you installed Syncthing in another way it will not work.

**Comment by QuentinWidlocher** [comment]
Ok thanks a lot for your answer, I'll do that then 👍
