### ISSUE TITLE
Syncthing-GTK different sync port and webUI port

### ISSUE THREAD

**Issue by coldfire0200** [theCapypara/steamdeck-decky-syncthing#5]
Not really a bug but something to note in case other people experience the similar problems.

I installed SyncthingGTK flatpak and for some reason the program uses port 8384 as sync port and 8081 for webUI. Seems to be all by default as I have not explicitly changed the settings. 

The decky-syncthing thus cannot access webUI (or open 127.0.0.1/58384). But syncthing service was able to start no problem. After I manually changed config.xml in syncthing everything works perfectly with the decky plugin.

**Comment by sam8457** [comment]
This thread also helped me, but just FYI for anyone who was stuck while trying to find the config.XML file, you can also change the ports in the web interface.

Just run Syncthing GTK, right click the tray icon, and select Open Web Interface. Then in your browser, click Actions, Settings, and under the GUI tab in the GUI Listen Address box enter 127.0.0.1:8384 , and under the Connections tab in the Sync Protocol Listen Address box change TCP://0.0.0.0:##### and quickly://0.0.0.0:##### to TCP://0.0.0.0:22000 and quickly://0.0.0.0:22000 , then click save. After that go back to game mode and run the setup for the syncthing plugin in Decky Loader again.

The issue for me ended up being caused by having syncthing tray installed prior to syncthing gtk, and I think GTK defaulted to a different set of ports to avoid collisions with the other flatpak.
